# Build
- docker build -t udagram-api-frontend ./udagram-frontend
# Do similar for other three images

# Tagging
- docker tag udagram-api-frontend tuankhoi2206/udagram-frontend:v1
# Do similar for other three images

# Push
# Assuming DOCKER_PASSWORD and DOCKER_USERNAME are set in the Travis repository settings
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker push tuankhoi2206/udagram-frontend:v1
# Do similar for other three images
